if (true) console.log('1');
if ({}) console.log('2');
if ([]) console.log('3');
if (42) console.log('4');
if ("0") console.log('5');
if ("false") console.log('6');
if (new Date()) console.log('7');
if (-42) console.log('8');
if (12n) console.log('9');
if (3.14) console.log('10');
if (-3.14) console.log('11');
if (Infinity) console.log('12');
if (-Infinity) console.log('13');
